// The Old Struct (For Reference)
// export interface Mod {
//     url?: string;
//     viewTransitionTag: string;
//     name: string;
//     console: string;
//     boxArtUrl: AssetData;
//     year: number;
// }

export interface Mod {
    displayName: string;
    internalName: string;

    tagline: string;
    description: string;

    creators: string[];
    releaseDate: string;
    lastUpdated: string;

    version: string;

    pageUrl?: string;
    sourceUrl?: string;
    iconUrl?: string;
    downloadUrl: string;

    game: string;
    console: string;
    consoleCompatible: boolean;
    recommendedEmulator: string;

    modGroup?: string;
    color?: string;
}

export const obj: { [key: string]: Mod } = {
    mq: {
        displayName: "Paper Mario: Master Quest",
        internalName: "pmmq",
        creators: [
            "Brotenko",
            "Emperor Thamz",
            "Quackles",
            "Rainchus",
            "snakemouth_den",
            "ShyBlookster",
            "Vinnie64",
            "Please Fill the Rest of the List In",
        ],
        releaseDate: "13/11/2019",
        lastUpdated: "20/02/2023",
        version: "1.5.1.1",
        downloadUrl:
            "https://github.com/Brotenko/PMMasterQuest/files/10786888/PMMQ_1.5.1.1.mod.zip",
        sourceUrl: "https://github.com/Brotenko/PMMasterQuest",
        iconUrl: "/src/routes/mods/assets/empty.webp?run&lqip=0",
        tagline: "The Dark Souls of Paper Mario",
        description:
            'Considered "The Dark Souls of Paper Mario", Master Quest is incredibly difficult.\n\nIt was designed with elite challenge runners in mind, and unless you have extensive knowledge of Paper Mario, you may struggle with much of the content.',
        game: "PM64",
        console: "N64",
        consoleCompatible: true,
        recommendedEmulator: "Ares",
        color: "#A020F0",
    },
    mqjr: {
        displayName: "Paper Mario: Master Quest JR",
        internalName: "pmmq_jr",
        creators: [
            "Brotenko",
            "Emperor Thamz",
            "Quackles",
            "Rainchus",
            "snakemouth_den",
            "ShyBlookster",
            "Vinnie64",
            "Please Fill the Rest of the List In",
        ],
        releaseDate: "13/11/2019",
        lastUpdated: "20/02/2023",
        version: "1.5.1.2",
        downloadUrl:
            "https://github.com/Brotenko/PMMasterQuest/files/10786890/PMMQ_Jr._1.5.1.2.mod.zip",
        sourceUrl: "https://github.com/Brotenko/PMMasterQuest",
        iconUrl: "/src/routes/mods/assets/empty.webp?run&lqip=0",
        tagline: "The Not-So Dark Souls of Paper Mario",
        description:
            "Master Quest JR is an easier version of Master Quest, for those who still want to experience the new content.\n\nHave fun!",
        game: "PM64",
        console: "N64",
        consoleCompatible: true,
        recommendedEmulator: "Ares",
        color: "#A020F0",
    },
    blackpit: {
        displayName: "Paper Mario: Black Pit",
        internalName: "blackpit",
        creators: ["eldexter", "Rainchus"],
        releaseDate: "20/07/2021",
        lastUpdated: "28/10/2023",
        version: "1.4.1",
        downloadUrl:
            "https://github.com/eldexterr/pmblackpit/releases/download/v1.4.1/BlackPit_v1.4.1.bps",
        sourceUrl: "https://github.com/eldexterr/pmblackpit",
        iconUrl: "/src/routes/mods/assets/empty.webp?run&lqip=0",
        tagline: "Challenge yourself inside the Pit!",
        description:
            "Black Pit is a mod about Mario in a pit.\n\nWill you survive?",
        game: "PM64",
        console: "N64",
        consoleCompatible: true,
        recommendedEmulator: "Ares",
        color: "#f00",
    },
    dse: {
        displayName: "Paper Mario: Dark Star Edition",
        internalName: "dse",
        creators: ["ShadeBlade"],
        releaseDate: "16/09/2021",
        lastUpdated: "24/06/2022",
        version: "1.5.3h5",
        downloadUrl:
            "https://github.com/Shade-Blade/PMDarkStarEdition/blob/main/DarkStarEdition%20v1.5.3h5.bps",
        sourceUrl: "https://github.com/Shade-Blade/PMDarkStarEdition",
        iconUrl: "/src/routes/mods/assets/empty.webp?run&lqip=0",
        tagline: "The Bloodborne of Paper Mario",
        description:
            "Paper Mario: Dark Star Edition is a mod for Paper Mario created by ShadeBlade that adds a lot of new content to the game and increases the difficulty.",
        game: "PM64",
        console: "N64",
        consoleCompatible: false,
        recommendedEmulator: "Bizhawk",
        color: "#00f",
    },
    fp: {
        displayName: "FP - Practice ROM",
        internalName: "fp",
        creators: ["JCog"],
        releaseDate: "28/06/2021",
        lastUpdated: "19/03/2024",
        version: "3.1",
        downloadUrl: "https://fp-patcher.starhaven.dev/",
        sourceUrl: "https://github.com/JCog/fp",
        iconUrl: "/src/routes/mods/assets/empty.webp?run&lqip=0",
        tagline: "Hone your skills!",
        description:
            "A mod intended for speedrun practice, glitch hunting, and just general game research.\nAmong many other things, it allows easy warping to locations, bosses, and speedrun tricks, easy editing of common game data, a real-time timer and lag frame counter, trainers for learning tricks, and customizable settings.",
        game: "PM64",
        console: "N64",
        consoleCompatible: true,
        recommendedEmulator: "Ares",
    },
    infinitepit: {
        displayName: "Infinite Pit",
        internalName: "infinitepit",
        creators: ["Jdaster64"],
        releaseDate: "19/07/2021",
        lastUpdated: "16/07/2023",
        version: "2.40",
        pageUrl:
            "https://docs.google.com/document/d/1H_6zmdJJ91q1poh6VtngCe_EqME-1gooF11u0hlE2qM/view",
        downloadUrl:
            "https://github.com/jdaster64/ttyd-infinite-pit/releases/download/v2.40/InfinitePit_v2_40_r64.gci",
        sourceUrl: "https://github.com/jdaster64/ttyd-infinite-pit",
        iconUrl: "/src/routes/mods/assets/emptyttyd.webp?run&lqip=0",
        tagline: "A roguelike Pit of 100 Trials!",
        description:
            "Paper Mario: TTYD Infinite Pit is a Roguelike mod of TTYD's Pit of 100 Trials by Jdaster64.\n\nIn it, Mario is pit against an endless series of random enemy fights, with random item drops, chest rewards, and more!",
        game: "TTYD",
        console: "GCN",
        consoleCompatible: true,
        recommendedEmulator: "Dolphin",
    },
    pm2: {
        displayName: "Paper Mario 2",
        internalName: "pm2",
        creators: ["snakemouth_den", "enneagon", "Wrymouth"],
        releaseDate: "01/06/2023",
        lastUpdated: "01/06/2023",
        version: "0.5",
        pageUrl: "https://snakemouth-den.itch.io/paper-mario-2",
        downloadUrl: "https://snakemouth-den.itch.io/paper-mario-2",
        sourceUrl: "https://snakemouth-den.itch.io/paper-mario-2",
        iconUrl: "/src/routes/mods/assets/2.webp?run&lqip=0",
        tagline: "The long awaited sequel!",
        description:
            "Wrymouth, Nine & Den proudly present: Paper Mario 2, sequel to popular JRPG Paper Mario.",
        game: "PM64",
        console: "N64",
        consoleCompatible: true,
        recommendedEmulator: "Ares",
    },
    wario: {
        displayName: "WARIO",
        internalName: "wario",
        creators: ["Miigle"],
        releaseDate: "29/08/2023",
        lastUpdated: "29/08/2023",
        version: "1.0",
        pageUrl: "https://miigle.itch.io/wario",
        downloadUrl: "https://miigle.itch.io/wario",
        sourceUrl: "https://github.com/Miigle-Rose/wario",
        iconUrl: "/src/routes/mods/assets/wario.webp?run&lqip=0",
        tagline: "WARIO!!!!!!!!!!",
        description:
            "WARIO!!!!!!!!!!\nExplore the Warioverse.\nWario.\nWario.\nWario.\nWario.\nWARIO!!!!!!!!!",
        game: "PM64",
        console: "N64",
        consoleCompatible: false,
        recommendedEmulator: "Ares",
        modGroup: "Jam2023",
        color: "#ff0",
    },
    pro: {
        displayName: "Paper Mario: Pro Mode",
        internalName: "pro",
        creators: ["nanaian", "Pro Mode Devs Pls Fill In :)"],
        releaseDate: "29/09/2017",
        lastUpdated: "16/10/2019",
        version: "0.1.6",
        downloadUrl:
            "https://drive.google.com/file/d/1AhXU1uScWzdQNu5jHWDFK-fXcHo4kcoF/view?usp=drive_link",
        sourceUrl:
            "https://www.dropbox.com/s/yf10myw0wi8p9ju/Paper%20Mario%20Pro%20Mode%20Source%20(beta%20r3)%20(2).zip?dl=0",
        iconUrl: "/src/routes/mods/assets/empty.webp?run&lqip=0",
        tagline: "The Original Hard Mode",
        description: "A difficulty mod for Paper Mario.",
        game: "PM64",
        console: "N64",
        consoleCompatible: true,
        recommendedEmulator: "Ares",
    },
    rando: {
        displayName: "Paper Mario Randomizer",
        internalName: "rando",
        creators: ["Pronyo", "Icebound777", "Rando Devs Pls Fill In :)"],
        releaseDate: "04/03/2022",
        lastUpdated: "29/06/2024",
        version: "0.27.1",
        downloadUrl: "https://pm64randomizer.com/",
        sourceUrl: "https://pm64randomizer.com/github",
        iconUrl: "/src/routes/mods/assets/empty.webp?run&lqip=0",
        tagline: "Random Fun!",
        description: "A randomiser for Paper Mario.",
        game: "PM64",
        console: "N64",
        consoleCompatible: true,
        recommendedEmulator: "simple64",
    },
    spmhard: {
        displayName: "Super Paper Mario: Hard Mode",
        internalName: "spmhard",
        creators: ["l5050", "Seeky"],
        releaseDate: "01/06/2023",
        lastUpdated: "08/05/2024",
        version: "2.1.1",
        pageUrl: "https://snakemouth-den.itch.io/paper-mario-2",
        downloadUrl:
            "https://github.com/L5050/SPM-Hard-Mode/releases/tag/V2.1.1",
        sourceUrl: "https://github.com/L5050/SPM-Hard-Mode",
        iconUrl: "/src/routes/mods/assets/emptyspm.webp?run&lqip=0",
        tagline: "Super Difficult!",
        description:
            "This mod attempts to make the gameplay a lot more appealing and difficult.\n\nXP, HP, damage and bosses have been reworked!",
        game: "SPM",
        console: "Wii",
        consoleCompatible: true,
        recommendedEmulator: "Dolphin",
    },
    ssttyd: {
        displayName: "Sticker Star: TTYD Style",
        internalName: "ssttyd",
        creators: ["Juggling Gamer"],
        releaseDate: "11/09/2023",
        lastUpdated: "17/10/2023",
        version: "1.2",
        pageUrl: "https://gamebanana.com/mods/461906",
        downloadUrl:
            "https://files.gamebanana.com/mods/paper_mario_sticker_star_ttyd_style_12.zip",
        sourceUrl: "https://gamebanana.com/mods/461906",
        iconUrl: "/src/routes/mods/assets/emptyss.webp?run&lqip=0",
        tagline: "New textures for Sticker Star!",
        description: "Makes Sticker Star look more like TTYD.",
        game: "SS",
        console: "3DS",
        consoleCompatible: true,
        recommendedEmulator: "???",
    },
    sweetex: {
        displayName: "Sweet Expedition",
        internalName: "sweetex",
        creators: ["JackitK"],
        releaseDate: "04/09/2022",
        lastUpdated: "09/12/2023",
        version: "1.0.3",
        downloadUrl:
            "https://github.com/JackitK/Paper-Mario-Sweet-Expedition/releases/download/v1.0.3/Sweet.Expedition.V1.0.3.bps",
        sourceUrl: "https://github.com/JackitK/Paper-Mario-Sweet-Expedition",
        iconUrl: "/src/routes/mods/assets/empty.webp?run&lqip=0",
        tagline: "A Real Treat!",
        description:
            "Paper Mario's Sweet Adventure is a mod for Paper Mario 64, featuring Mario's adventure to a new land called Glace Island.\n\nKolorado has heard rumors of a grand treasure that lies there, and he needs Mario's help to retrieve it.",
        game: "PM64",
        console: "N64",
        consoleCompatible: true,
        recommendedEmulator: "Ares",
        modGroup: "Jam2022",
    },
    parable: {
        displayName: "The Paper Parable",
        internalName: "parable",
        creators: ["Enneagon"],
        releaseDate: "01/05/2023",
        lastUpdated: "01/05/2023",
        version: "1.2.4",
        pageUrl: "https://enneagon.itch.io/the-paper-parable",
        downloadUrl: "https://enneagon.itch.io/the-paper-parable",
        iconUrl: "/src/routes/mods/assets/empty.webp?run&lqip=0",
        tagline: "This is the story of a man named Mario.",
        description:
            "The Paper Parable is a Paper Mario-flavoured remix of The Stanley Parable. You will play as Mario, and you will not play as Mario. Your choices will matter, and your choices will be meaningless. You will solve the mystery of Princess Peach's disappearance, and you will be forever left in the dark.",
        game: "PM64",
        console: "N64",
        consoleCompatible: true,
        recommendedEmulator: "Ares",
    },
    ttyd64: {
        displayName: "Paper Mario: TTYD64",
        internalName: "ttyd64",
        creators: ["elDexter"],
        releaseDate: "20/12/2023",
        lastUpdated: "20/12/2023",
        version: "1.0.0",
        downloadUrl:
            "https://github.com/eldexterr/ttyd64/releases/download/sourceCode/TTYD64-v1.0.0.bps",
        sourceUrl: "https://github.com/eldexterr/ttyd64",
        iconUrl: "/src/routes/mods/assets/empty.webp?run&lqip=0",
        tagline: "Old Game, New Features!",
        description:
            "TTYD64 is a PM64 romhack that adds TTYD's gameplay, items, badges, and recipes into PM64, plus a bunch of new areas into the game.",
        game: "PM64",
        console: "N64",
        consoleCompatible: true,
        recommendedEmulator: "Ares",
    },
    xmas1: {
        displayName: "Paper Mario: Christmas Special",
        internalName: "xmas",
        creators: [
            "Snakemouth_Den",
            "Wrymouth",
            "Fewffwa",
            "nanaian",
            "Pls fill in :)",
        ],
        releaseDate: "25/12/2021",
        lastUpdated: "25/12/2021",
        version: "1.0.0",
        downloadUrl:
            "https://drive.google.com/file/d/1fB76FOv_wrnmw6nLhox9enq_XMJWtu0V/view?usp=drive_link",
        sourceUrl:
            "https://drive.google.com/file/d/1fB76FOv_wrnmw6nLhox9enq_XMJWtu0V/view?usp=drive_link",
        iconUrl: "/src/routes/mods/assets/empty.webp?run&lqip=0",
        tagline: "A Christmas Miracle!",
        description:
            "Merry Christmas everyone, this is our gift to you, made in only 19 days.\nWe hope you enjoy it just as much as we enjoyed making it.\n\nAnd if you don't... there is a Gulpit rapidly approaching your location :)",
        game: "PM64",
        console: "N64",
        consoleCompatible: true,
        recommendedEmulator: "Ares",
    },
    xmas2: {
        displayName: "Paper Mario: Christmas Special 2",
        internalName: "xmas2",
        creators: [
            "Snakemouth_Den",
            "Wrymouth",
            "Fewffwa",
            "nanaian",
            "Miigle",
            "Pls fill in :)",
        ],
        releaseDate: "25/12/2022",
        lastUpdated: "25/12/2022",
        version: "0.1",
        downloadUrl:
            "https://drive.google.com/file/d/1J0GPtfLqFn2Li4ZYe2DcWTeQaShh_0wI/view?usp=drive_link",
        iconUrl: "/src/routes/mods/assets/empty.webp?run&lqip=0",
        tagline: "A Christmas Demo!",
        description:
            "Merry chrimstas!\nWe hope you enjoy this teaser for the whole thing we whipped up :>\n\nI wish you all happy holidays!!",
        game: "PM64",
        console: "N64",
        consoleCompatible: true,
        recommendedEmulator: "Ares",
    },
    hero: {
        displayName: "Paper Mario: Hero Mode",
        internalName: "hero",
        creators: ["Reed"],
        releaseDate: "09/01/2023",
        lastUpdated: "14/04/2024",
        version: "4.0.3 Demo",
        pageUrl:
            "https://github.com/Reeds-github/Hero-Mode?tab=readme-ov-file#before-anything-you-must-read-this",
        downloadUrl:
            "https://github.com/Reeds-github/Hero-Mode/releases/tag/v4.0.3",
        sourceUrl: "https://github.com/Reeds-github/Hero-Mode",
        iconUrl: "/src/routes/mods/assets/empty.webp?run&lqip=0",
        tagline: "A Heroic Adventure!",
        description:
            "A reimagined The Thousand-Year Door story that comes with new puzzles, harder difficulty, badges, items, and more twists!\n\nHero Mode is intended for 'professional players,' but can be also played by 'casual players' too!",
        game: "TTYD",
        console: "GCN",
        consoleCompatible: true,
        recommendedEmulator: "Dolphin",
    },
    tiaw: {
        displayName: "Thamz in a Wheelchair",
        internalName: "tiaw",
        creators: ["Wrymouth"],
        releaseDate: "15/08/2021",
        lastUpdated: "15/08/2021",
        version: "1.1.1",
        downloadUrl:
            "https://drive.google.com/file/d/160i43cEq7ysRvCX6lT7WjKIuB2OP46V2/view?usp=sharing",
        iconUrl: "/src/routes/mods/assets/empty.webp?run&lqip=0",
        tagline: "Thamz In A Wheelchair",
        description: "weegee",
        game: "PM64",
        console: "N64",
        consoleCompatible: true,
        recommendedEmulator: "Ares",
    },
    bus: {
        displayName: "Paper Desert Bus",
        internalName: "bus",
        creators: ["Fewffwa"],
        releaseDate: "02/10/2021",
        lastUpdated: "02/10/2021",
        version: "1.1.0",
        downloadUrl:
            "https://drive.google.com/file/d/1tJJDJVG-AljTKiLIwbaUbTP9_kXbNsWd/view?usp=sharing",
        iconUrl: "/src/routes/mods/assets/empty.webp?run&lqip=0",
        tagline: "It's Desert Bus!",
        description:
            "Experience the incredible Desert Bus, in Paper Mario form!",
        game: "PM64",
        console: "N64",
        consoleCompatible: true,
        recommendedEmulator: "Ares",
    },
    cylinder: {
        displayName: "The Cylinder of Wood",
        internalName: "cylinder",
        creators: ["Toonbink"],
        releaseDate: "11/08/2020",
        lastUpdated: "11/08/2020",
        version: "1.0",
        downloadUrl:
            "https://drive.google.com/file/d/1mvnr3mSMR2KXJVsdjAO_O3mbkxsdDbOv/view?usp=sharing",
        iconUrl: "/src/routes/mods/assets/empty.webp?run&lqip=0",
        tagline: "Cylindrical!",
        description:
            "No New Areas!\n\nA single new structure!\n\nHistorical value!",
        game: "PM64",
        console: "N64",
        consoleCompatible: true,
        recommendedEmulator: "Ares",
    },
    memeio: {
        displayName: "Paper Memeio 69",
        internalName: "memeio",
        creators: ["Count Homer"],
        releaseDate: "17/08/2020",
        lastUpdated: "17/08/2020",
        version: "0.0.69",
        downloadUrl:
            "https://github.com/CountHomer69/Paper-Memeio-69/blob/6d555334b8c973ab699c1b45c5731ced56648139/out/Paper%20Memeio%2069%200.0.69.mod",
        sourceUrl: "https://github.com/CountHomer69/Paper-Memeio-69",
        iconUrl: "/src/routes/mods/assets/empty.webp?run&lqip=0",
        tagline: "Friggity Sweet!",
        description: "The most awesome and epic mod, Paper Memeio 69, is here!",
        game: "PM64",
        console: "N64",
        consoleCompatible: true,
        recommendedEmulator: "Ares",
    },
    textless: {
        displayName: "Textless Paper Mario",
        internalName: "textless",
        creators: ["quickenfixen"],
        releaseDate: "27/09/2021",
        lastUpdated: "27/09/2021",
        version: "0.2",
        downloadUrl:
            "https://github.com/quickenfixen/TextlessPM/releases/download/v0.2/TextlessPM.v0.2.mod",
        sourceUrl: "https://github.com/quickenfixen/TextlessPM",
        iconUrl: "/src/routes/mods/assets/blank.webp?run&lqip=0",
        tagline: " ",
        description: " ",
        game: "PM64",
        console: "N64",
        consoleCompatible: true,
        recommendedEmulator: "Ares",
    },
    mogus: {
        displayName: "Paper Mogus",
        internalName: "mogus",
        creators: ["Sussy Gaming"],
        releaseDate: "27/09/2021",
        lastUpdated: "27/09/2021",
        version: "0.1 Demo",
        downloadUrl:
            "https://drive.google.com/file/d/1ksFdecgM03hgLeZSCBTD18UBJszNViNg/view?usp=drive_link",
        iconUrl: "/src/routes/mods/assets/empty.webp?run&lqip=0",
        tagline: "Feeling Sussy?",
        description: "The mod is Among Us!",
        game: "PM64",
        console: "N64",
        consoleCompatible: true,
        recommendedEmulator: "Ares",
    },
    allbosses: {
        displayName: "All Bosses",
        internalName: "allbosses",
        creators: ["elDexter"],
        releaseDate: "26/12/2021",
        lastUpdated: "26/12/2021",
        version: "1.0.1",
        downloadUrl:
            "https://www.mediafire.com/file/r1jx6syuq12sefz/PM_AllBosses_v1.0.1.bps/file",
        sourceUrl: "https://github.com/eldexterr/allbosses",
        iconUrl: "/src/routes/mods/assets/empty.webp?run&lqip=0",
        tagline: "The Ultimate Challenge!",
        description: "Can you beat every boss at once?",
        game: "PM64",
        console: "N64",
        consoleCompatible: true,
        recommendedEmulator: "Ares",
    },
    photohelper: {
        displayName: "TOK Photo Helper",
        internalName: "photohelper",
        creators: ["Darxoon"],
        releaseDate: "18/02/2022",
        lastUpdated: "18/02/2022",
        version: "1.0",
        downloadUrl: "https://gamebanana.com/mods/341277",
        pageUrl: "https://gamebanana.com/mods/341277",
        iconUrl: "/src/routes/mods/assets/emptytok.webp?run&lqip=0",
        tagline: "Camera Tool",
        description:
            "Removes the HUD (and optionally Mario) for beautiful screenshots",
        game: "TOK",
        console: "Switch",
        consoleCompatible: true,
        recommendedEmulator: "Ryujinx",
    },
    luigi: {
        displayName: "Luigi as a Partner",
        internalName: "luigi",
        creators: ["Helldoom"],
        releaseDate: "30/06/2022",
        lastUpdated: "30/06/2022",
        version: "1.0",
        downloadUrl:
            "https://www.mediafire.com/file/erc6q618s3i5rij/Paper_Mario_Luigi_Partner_Mod.mod/file",
        iconUrl: "/src/routes/mods/assets/empty.webp?run&lqip=0",
        tagline: "Wahoo!",
        description: "Luigi is added as a partner!",
        game: "PM64",
        console: "N64",
        consoleCompatible: true,
        recommendedEmulator: "Ares",
    },
    haunt: {
        displayName: "Haunted Paper Mario",
        internalName: "haunt",
        creators: ["ShyBlookster137"],
        releaseDate: "23/06/2024",
        lastUpdated: "25/06/2024",
        version: "1.1",
        pageUrl: "https://shyblookster137.itch.io/haunted-paper-mario",
        downloadUrl: "https://shyblookster137.itch.io/haunted-paper-mario",
        iconUrl: "/src/routes/mods/assets/empty.webp?run&lqip=0",
        tagline: "It's Haunted.",
        description:
            "You retrieve a haunted copy of Paper Mario for the Nintendo 64 from an unsuspecting corner of the internet.\n\nWas this a mistake?",
        game: "PM64",
        console: "N64",
        consoleCompatible: true,
        recommendedEmulator: "Ares",
    },
    toadette: {
        displayName: "Toadette Over Mario",
        internalName: "toadette",
        creators: ["acht05"],
        releaseDate: "07/04/2024",
        lastUpdated: "07/04/2024",
        version: "1.0",
        pageUrl: "https://gamebanana.com/mods/505581",
        downloadUrl: "https://gamebanana.com/mods/505581",
        iconUrl: "/src/routes/mods/assets/empty.webp?run&lqip=0",
        tagline: "Play as Toadette!",
        description: "aka Paper Mario featuring Toadette....",
        game: "PM64",
        console: "N64",
        consoleCompatible: true,
        recommendedEmulator: "Ares",
    },
    goombavillage: {
        displayName: "Escape from Goomba Village",
        internalName: "goombavillage",
        creators: ["truttle1"],
        releaseDate: "05/08/2024",
        lastUpdated: "05/08/2024",
        version: "1.0",
        downloadUrl:
            "https://www.dropbox.com/scl/fi/osthuc3v4sg7932aimw9x/EscapeGoombaVillageV2.zip?rlkey=b9bjih6p0o3vqorfmkdugk1ex&dl=0",
        iconUrl: "/src/routes/mods/assets/empty.webp?run&lqip=0",
        tagline: "GUESS WHO'S BACK!?!?",
        description:
            "I've kidnapped the princess again (please don't check how many times it's been). This time though, I know things will be different. And yeah, I know that I say that every time, but this time, I've got the STAR ROD!!! This awesome device lets me change Paper Mario 64 to WHATEVER I WANT!!!...",
        game: "PM64",
        console: "N64",
        consoleCompatible: true,
        recommendedEmulator: "Ares",
    },
    dr2022: {
        displayName: "Paper Dank Rave 2022 edition Dank%",
        internalName: "dr2022",
        creators: ["Nonagon"],
        releaseDate: "15/04/2022",
        lastUpdated: "15/04/2022",
        version: "1.0",
        pageUrl: "https://enneagon.itch.io/paper-dank-rave",
        downloadUrl: "https://enneagon.itch.io/paper-dank-rave",
        iconUrl: "/src/routes/mods/assets/dank.webp?run&lqip=0",
        tagline: "The Dankest Mod Ever!",
        description:
            "Loosely inspired by the Bowser's Dank Rave series of mods for Super Mario 64, this Paper Mario 64 mod was created in just two days and contains about 5-10 minutes of gameplay.\n\nHappy raving, everyone!",
        game: "PM64",
        console: "N64",
        consoleCompatible: true,
        recommendedEmulator: "Ares",
    },
    dr2023: {
        displayName: "Paper Dank Rave 2023 edition Dank%",
        internalName: "dr2023",
        creators: ["Nonagon"],
        releaseDate: "15/04/2023",
        lastUpdated: "15/04/2023",
        version: "1.0",
        pageUrl: "https://enneagon.itch.io/paper-dank-rave-2",
        downloadUrl: "https://enneagon.itch.io/paper-dank-rave-2",
        iconUrl: "/src/routes/mods/assets/dank.webp?run&lqip=0",
        tagline: "The Dankest Mod Ever! Again!",
        description:
            "Loosely inspired by the Bowser's Dank Rave series of mods for Super Mario 64, this sequel to a Paper Mario 64 mod was created in just two days and contains about 5-10 minutes of gameplay.\n\nHappy raving, everyone!",
        game: "PM64",
        console: "N64",
        consoleCompatible: true,
        recommendedEmulator: "Ares",
    },
    dr2024: {
        displayName: "Paper Dank Rave 2024 edition Dank%",
        internalName: "dr2024",
        creators: ["Nonagon"],
        releaseDate: "27/04/2024",
        lastUpdated: "27/04/2024",
        version: "1.0",
        pageUrl: "https://enneagon.itch.io/paper-dank-rave-3",
        downloadUrl: "https://enneagon.itch.io/paper-dank-rave-3",
        iconUrl: "/src/routes/mods/assets/dank.webp?run&lqip=0",
        tagline: "Now a yearly tradition!",
        description:
            "Loosely inspired by the Bowser's Dank Rave series of mods for Super Mario 64, this yearly continuation of a Paper Mario 64 mod was created in just two days and contains about 5-10 minutes of gameplay.\n\nHappy raving, everyone!",
        game: "PM64",
        console: "N64",
        consoleCompatible: true,
        recommendedEmulator: "Ares",
    },
    goomboss: {
        displayName: "Ultimate Goomboss Challenge",
        internalName: "goomboss",
        creators: ["Nonagon"],
        releaseDate: "19/03/2024",
        lastUpdated: "19/03/2024",
        version: "1.0",
        pageUrl: "https://enneagon.itch.io/ultimate-goomboss-challenge",
        downloadUrl: "https://enneagon.itch.io/ultimate-goomboss-challenge",
        iconUrl: "/src/routes/mods/assets/empty.webp?run&lqip=0",
        tagline: "Think you're strong enough?",
        description:
            "Saving the world is hungry work. With the Star Rod recovered, a satisfied Mario and Goombario head out for a bite to eat.\nBut who's this in their favourite picnic spot?\nAnd more importantly, can you come up with a strategy to defeat...\nTHE ULTIMATE GOOMBOSS CHALLENGE?",
        game: "PM64",
        console: "N64",
        consoleCompatible: true,
        recommendedEmulator: "Ares",
    },
    egghunt: {
        displayName: "Eggstraordinary Egg Hunt",
        internalName: "egghunt",
        creators: ["Snakemouth_Den", "Miigle"],
        releaseDate: "09/04/2023",
        lastUpdated: "09/04/2023",
        version: "1.0",
        pageUrl: "https://den01.itch.io/pm-eggstraordinary-egg-hunt",
        downloadUrl: "https://den01.itch.io/pm-eggstraordinary-egg-hunt",
        iconUrl: "/src/routes/mods/assets/Egg.webp?run&lqip=0",
        tagline: "An Eggstraordinary Adventure!",
        description:
            "Join Mario & Luigi for the annual Easter Egg Hunt in Toad Town and close regions like Koopa Village and Shooting Star Summit!",
        game: "PM64",
        console: "N64",
        consoleCompatible: true,
        recommendedEmulator: "Ares",
    },
    uwu: {
        displayName: "Papew Mawiowo",
        internalName: "uwu",
        creators: ["Pokemonhacker1337"],
        releaseDate: "09/04/2023",
        lastUpdated: "09/04/2023",
        version: "1.0",
        downloadUrl:
            "https://github.com/PokemonHacker1337/Misc-Projects/raw/main/PapewMawiowo.mod",
        iconUrl: "/src/routes/mods/assets/empty.webp?run&lqip=0",
        tagline: "OwO",
        description: "Paper Mario 64, uwu-ified!",
        game: "PM64",
        console: "N64",
        consoleCompatible: true,
        recommendedEmulator: "Ares",
    },
    tae: {
        displayName: "PM: 20th Anniversary Edition",
        internalName: "tae",
        creators: ["Count Homer"],
        releaseDate: "11/08/2020",
        lastUpdated: "11/08/2020",
        version: "1.?",
        downloadUrl:
            "https://drive.google.com/file/d/1ZZVm0uoW2uzDOuxt4xzJqYZ3wdpuDoKN/view?usp=sharing",
        iconUrl: "/src/routes/mods/assets/empty.webp?run&lqip=0",
        tagline: "Happy Anniversary!",
        description:
            "Paper Mario 64 with QoL changes to celebrate the 20th anniversary.",
        game: "PM64",
        console: "N64",
        consoleCompatible: true,
        recommendedEmulator: "Ares",
    },
    bib: {
        displayName: "Paper Mario: Back in Bowser",
        internalName: "bib",
        creators: ["N8", "Rain"],
        releaseDate: "13/06/2022",
        lastUpdated: "13/06/2022",
        version: "1.0",
        sourceUrl: "https://github.com/Rainchus/pm-jam",
        downloadUrl: "https://n8-typo.itch.io/pm-bib",
        pageUrl: "https://n8-typo.itch.io/pm-bib",
        iconUrl: "/src/routes/mods/assets/empty.webp?run&lqip=0",
        tagline: "Back in Bowser!",
        description:
            "Team up with Starlow in this proof-of-concept Paper Mario 64 ROM Hack! Battle familiar foes, use new abilities, and try your best to escape Bowser's body!",
        game: "PM64",
        console: "N64",
        consoleCompatible: true,
        recommendedEmulator: "Ares",
        modGroup: "Jam2022",
    },
    cook: {
        displayName: "Cooking Princess",
        internalName: "cook",
        creators: ["elDexter"],
        releaseDate: "13/06/2022",
        lastUpdated: "28/06/2022",
        version: "1.0",
        downloadUrl: "https://eldexter.itch.io/cooking-princess",
        pageUrl: "https://eldexter.itch.io/cooking-princess",
        iconUrl: "/src/routes/mods/assets/empty.webp?run&lqip=0",
        tagline: "It's Like Overcooked!",
        description:
            "Surpass cooking-based time attack levels and make the largest amount of toads happy (or unhappy) with your bakery.",
        game: "PM64",
        console: "N64",
        consoleCompatible: true,
        recommendedEmulator: "Ares",
        modGroup: "Jam2022",
    },
    cc: {
        displayName: "Paper Mario: Cake Chaos",
        internalName: "cc",
        creators: ["Snakemouth_den", "Fewffwa"],
        releaseDate: "31/05/2022",
        lastUpdated: "31/05/2022",
        version: "1.0",
        downloadUrl: "https://fewffwa.itch.io/paper-mario-cake-chaos",
        pageUrl: "https://fewffwa.itch.io/paper-mario-cake-chaos",
        iconUrl: "/src/routes/mods/assets/empty.webp?run&lqip=0",
        tagline: "Chaotic!",
        description:
            "Waking up in a land of food, Mario must deliver ingredients to a familiar foe...",
        game: "PM64",
        console: "N64",
        consoleCompatible: true,
        recommendedEmulator: "Ares",
        modGroup: "Jam2022",
    },
    iq1: {
        displayName: "Gourmet Guy's 1000IQ Food Quiz",
        internalName: "cc",
        creators: ["Wrymouth"],
        releaseDate: "05/06/2022",
        lastUpdated: "05/06/2022",
        version: "1.0",
        downloadUrl: "https://wrymouth.itch.io/gourmet-guys-1000iq-food-quiz",
        pageUrl: "https://wrymouth.itch.io/gourmet-guys-1000iq-food-quiz",
        iconUrl: "/src/routes/mods/assets/empty.webp?run&lqip=0",
        tagline: "Quizzical!",
        description: "Help Gourmet Guy win the 1000 IQ Food Quiz!",
        game: "PM64",
        console: "N64",
        consoleCompatible: true,
        recommendedEmulator: "Ares",
        modGroup: "Jam2022",
    },
    flour: {
        displayName: "Paper Peach: Flour Power",
        internalName: "flour",
        creators: ["Miigle"],
        releaseDate: "10/06/2022",
        lastUpdated: "10/06/2022",
        version: "0.1",
        downloadUrl: "https://miigle.itch.io/peachcook64",
        pageUrl: "https://miigle.itch.io/peachcook64",
        iconUrl: "/src/routes/mods/assets/empty.webp?run&lqip=0",
        tagline: "Don't Play This One.",
        description:
            "Princess Peach needs to cook for Gourmet Guy! Can you do it?\nPlay over [1] exciting minigames where you need to cook!\nCan you beat the secret ending?",
        game: "PM64",
        console: "N64",
        consoleCompatible: true,
        recommendedEmulator: "Ares",
        modGroup: "Jam2022",
    },
    newyear: {
        displayName: "Paper Mario: Saving New Years",
        internalName: "newyear",
        creators: ["Wrymouth"],
        releaseDate: "31/12/2022",
        lastUpdated: "31/12/2022",
        version: "1.0",
        downloadUrl: "https://wrymouth.itch.io/paper-mario-saving-new-years",
        pageUrl: "https://wrymouth.itch.io/paper-mario-saving-new-years",
        iconUrl: "/src/routes/mods/assets/empty.webp?run&lqip=0",
        tagline: "Can YOU save New Years?",
        description:
            "Mario faces a new enemy. If he doesn't win, 2022 may never end...",
        game: "PM64",
        console: "N64",
        consoleCompatible: true,
        recommendedEmulator: "Ares",
    },
    blocks: {
        displayName: "Blocks of Wisdom",
        internalName: "blocks",
        creators: ["Tartt"],
        releaseDate: "22/10/2024",
        lastUpdated: "29/10/2024",
        version: "2.0",
        downloadUrl:
            "https://github.com/shiken-yme/blocks-of-wisdom/releases/latest",
        sourceUrl: "https://github.com/shiken-yme/blocks-of-wisdom",
        iconUrl: "/src/routes/mods/assets/emptyspm.webp?run&lqip=0",
        tagline: "Spawn blocks anywhere!",
        description:
            "A mod that allows you to spawn and customize up to 5 blocks in nearly any room in the game.",
        game: "SPM",
        console: "Wii",
        consoleCompatible: true,
        recommendedEmulator: "Dolphin",
    },
    spmpr: {
        displayName: "Flipside Pit Randomizer",
        internalName: "spmpr",
        creators: ["Tartt"],
        releaseDate: "31/08/2024",
        lastUpdated: "29/09/2024",
        version: "0.1.2",
        downloadUrl:
            "https://github.com/shiken-yme/spm-pit-randomizer/releases/latest",
        sourceUrl: "https://github.com/shiken-yme/spm-pit-randomizer",
        iconUrl: "/src/routes/mods/assets/emptyspm.webp?run&lqip=0",
        tagline: "An all-new Pit experience!",
        description:
            "Randomizes the contents of the Flipside Pit of 100 Trials, adds new enemies, and rebalances others.",
        game: "SPM",
        console: "Wii",
        consoleCompatible: true,
        recommendedEmulator: "Dolphin",
    },
    tot: {
        displayName: "Tower of Trials",
        internalName: "tot",
        creators: ["Jdaster64"],
        releaseDate: "21/10/2024",
        lastUpdated: "29/10/2024",
        version: "1.1",
        pageUrl: "https://bit.ly/tower-of-trials-guide",
        downloadUrl: "https://github.com/jdaster64/ttyd-tot/releases/latest",
        sourceUrl: "https://github.com/jdaster64/ttyd-tot/releases",
        iconUrl: "/src/routes/mods/assets/emptyttyd.webp?run&lqip=0",
        tagline: "A Rogue-Like Race!",
        description:
            "Tower of Trials is a Rogue-like mod of Paper Mario: TTYD by Jdaster64.\nIn it, Mario storms the newly-renovated Hooktail Castle, fighting through a battery of enemy encounters and building up an arsenal of party members, moves, badges and other rewards!",
        game: "TTYD",
        console: "GCN",
        consoleCompatible: true,
        recommendedEmulator: "Dolphin",
    },
    sacred: {
        displayName: "Paper Mario: Sacred Trio",
        internalName: "sacred",
        creators: ["NicTube"],
        releaseDate: "29/08/2023",
        lastUpdated: "29/08/2023",
        version: "1.4",
        pageUrl: "https://nictuber.itch.io/paper-mario-sacred-trio",
        downloadUrl: "https://nictuber.itch.io/paper-mario-sacred-trio",
        sourceUrl: "https://github.com/NicTube/pm-sacred-trio-src",
        iconUrl: "/src/routes/mods/assets/empty.webp?run&lqip=0",
        tagline: "A new little adventure in the Great Cosmos!",
        description:
            "Join Mario for a new little adventure in the Great Cosmos! Team up with your new partner Salmos, who has the ability to float straight through space!",
        game: "PM64",
        console: "N64",
        consoleCompatible: true,
        recommendedEmulator: "Ares",
        modGroup: "Jam2023",
    },
    float: {
        displayName: "Paper Mario and the Floating Islands",
        internalName: "sacred",
        creators: ["PKsLab"],
        releaseDate: "29/08/2023",
        lastUpdated: "29/08/2023",
        version: "1.0",
        pageUrl: "https://pkslab.itch.io/paper-mario-and-the-floating-islands",
        downloadUrl:
            "https://pkslab.itch.io/paper-mario-and-the-floating-islands",
        iconUrl: "/src/routes/mods/assets/empty.webp?run&lqip=0",
        tagline: "A short and sweet mod of PM64 :)",
        description:
            "(DONT TALK DIRECTLY TO THE RED YOSHI, IT SOFTLOCKES YOUR GAME) This mod is extremely short btw, it can last up to 10 minutes if quickly played. It's main premise is that Mario is on a Floating Island and he has to travel to the North Island to defeat Kent C. Koopa who has taken rule over the island.",
        game: "PM64",
        console: "N64",
        consoleCompatible: true,
        recommendedEmulator: "Ares",
        modGroup: "Jam2023",
    },
    lss: {
        displayName: "Paper Mario: The Legendary Star Ship",
        internalName: "lss",
        creators: ["Wrymouth"],
        releaseDate: "29/08/2023",
        lastUpdated: "29/08/2023",
        version: "1.0",
        pageUrl:
            "https://wrymouth.itch.io/paper-mario-and-the-legendary-star-ship",
        downloadUrl:
            "https://wrymouth.itch.io/paper-mario-and-the-legendary-star-ship",
        sourceUrl: "https://github.com/Wrymouth/pm-space-game/tree/mod-src",
        iconUrl: "/src/routes/mods/assets/empty.webp?run&lqip=0",
        tagline: "A dangerous flight...",
        description:
            "Join Mario for a new little adventure in the Great Cosmos! Team up with your new partner Salmos, who has the ability to float straight through space!",
        game: "PM64",
        console: "N64",
        consoleCompatible: true,
        recommendedEmulator: "Ares",
        modGroup: "Jam2023",
    },
    flud: {
        displayName: "Paper Mario: 5 Letters until Doom",
        internalName: "flud",
        creators: ["Shyblookster137", "Snakemouth_Den", "Darxoon"],
        releaseDate: "29/08/2023",
        lastUpdated: "02/09/2023",
        version: "1.11",
        pageUrl: "https://shyblookster137.itch.io/pm-five-letters-until-doom",
        downloadUrl:
            "https://shyblookster137.itch.io/pm-five-letters-until-doom",
        sourceUrl: "https://github.com/Den1604/space-jam",
        iconUrl: "/src/routes/mods/assets/empty.webp?run&lqip=0",
        tagline: "Deliver some mail on time.",
        description:
            "Play as Mario and aid Parakarry in this cosmic adventure on a letter delivery escapade which trancends space and... space? (Time travel has not yet been invented, sorry.)",
        game: "PM64",
        console: "N64",
        consoleCompatible: true,
        recommendedEmulator: "Ares",
        modGroup: "Jam2023",
    },
    tn: {
        displayName: "Tatanga's Nebula",
        internalName: "tn",
        creators: ["Enneagon", "Ponderman", "Manapesto"],
        releaseDate: "29/08/2023",
        lastUpdated: "29/08/2023",
        version: "0.1",
        pageUrl: "https://enneagon.itch.io/tatangas-nebula-demo",
        downloadUrl: "https://enneagon.itch.io/tatangas-nebula-demo",
        iconUrl: "/src/routes/mods/assets/empty.webp?run&lqip=0",
        tagline: "An FTL-inspired adventure!",
        description:
            "That evil alien Tatanga has kidnapped Princess Peach. It's up to Paper Mario and the Sarasaland Space Agency to get her back!",
        game: "PM64",
        console: "N64",
        consoleCompatible: true,
        recommendedEmulator: "Ares",
        modGroup: "Jam2023",
    },
    windex: {
        displayName: "Brobot After Some Windex",
        internalName: "windex",
        creators: ["L5050"],
        releaseDate: "29/08/2023",
        lastUpdated: "05/03/2024",
        version: "1.22",
        sourceUrl: "https://github.com/L5050/Brobot-After-Some-Windex",
        pageUrl: "https://l5050.itch.io/brobot-after-some-windex",
        downloadUrl:
            "https://github.com/L5050/Brobot-After-Some-Windex/releases/latest",
        iconUrl: "/src/routes/mods/assets/emptyspm.webp?run&lqip=0",
        tagline: "Fight Brobot in a New Adventure!",
        description:
            "A cosmic themed modification of Super Paper Mario for the Paper Mario Modding Jam!",
        game: "SPM",
        console: "Wii",
        consoleCompatible: true,
        recommendedEmulator: "Dolphin",
        modGroup: "Jam2023",
    },
    millioniq: {
        displayName: "1,000,000IQ Cosmic-Brained Quiz",
        internalName: "millioniq",
        creators: ["fewffwa"],
        releaseDate: "29/08/2023",
        lastUpdated: "29/08/2023",
        version: "1.0",
        pageUrl:
            "https://fewffwa.itch.io/gourmet-guys-1000000-iq-cosmic-brained-quiz",
        downloadUrl:
            "https://fewffwa.itch.io/gourmet-guys-1000000-iq-cosmic-brained-quiz",
        iconUrl: "/src/routes/mods/assets/empty.webp?run&lqip=0",
        tagline: "Presented by Gourmet Guy!",
        description:
            "It's Gourmet Guy's 1,000,000 IQ Cosmic-Brained Quiz!\nCan you take home the ultimate prize?",
        game: "PM64",
        console: "N64",
        consoleCompatible: true,
        recommendedEmulator: "Ares",
        modGroup: "Jam2023",
    },
    ggebfb: {
        displayName: "Extravagant Boss Fight Bonanza",
        internalName: "ggebfb",
        creators: ["Snakemouth Den"],
        releaseDate: "06/05/2024",
        lastUpdated: "06/05/2024",
        version: "1.1",
        pageUrl:
            "https://snakemouth-den.itch.io/gourmet-guys-extravagant-boss-fight-bonanza",
        downloadUrl:
            "https://snakemouth-den.itch.io/gourmet-guys-extravagant-boss-fight-bonanza",
        sourceUrl: "https://github.com/Den1604/BattleHack",
        iconUrl: "/src/routes/mods/assets/empty.webp?run&lqip=0",
        tagline: "Presented by Gourmet Guy!",
        description:
            "Gourmet Guy stole the Star Rod from Star Haven! Now it is up to Mario to save the day once again. Can you defeat Gourmet Guy and retrieve the Star Rod for the Star Spirits, and restore peace in the Mushroom Kingdom?",
        game: "PM64",
        console: "N64",
        consoleCompatible: true,
        recommendedEmulator: "Ares",
        modGroup: "BattleJam2024",
    },
    retro: {
        displayName: "Paper Mario: Retro Rumble",
        internalName: "retro",
        creators: ["Wrymouth"],
        releaseDate: "06/05/2024",
        lastUpdated: "06/05/2024",
        version: "1.0",
        pageUrl: "https://wrymouth.itch.io/paper-mario-retro-rumble",
        downloadUrl: "https://wrymouth.itch.io/paper-mario-retro-rumblea",
        sourceUrl: "https://github.com/Wrymouth/pm-space-game/tree/mod-src",
        iconUrl: "/src/routes/mods/assets/soretro.webp?run&lqip=0",
        tagline: "Face off against some exciting new foes!",
        description:
            "The most rushed mod I've made in a bit. There's a few new enemies, and they all have 2-3 attacks each. Two custom songs as well, of which one new and one reused from my last mod.",
        game: "PM64",
        console: "N64",
        consoleCompatible: true,
        recommendedEmulator: "Ares",
        modGroup: "BattleJam2024",
    },
    koopamancer: {
        displayName: "The Koopamancer's Fury",
        internalName: "koopamancer",
        creators: ["T00nbink"],
        releaseDate: "06/05/2024",
        lastUpdated: "06/05/2024",
        version: "1.0",
        pageUrl: "https://t00nbink.itch.io/thekoopamancer",
        downloadUrl: "https://t00nbink.itch.io/thekoopamancer",
        sourceUrl: "https://github.com/LuukvanEck/TheKoopamancerFury",
        iconUrl: "/src/routes/mods/assets/empty.webp?run&lqip=0",
        tagline: "Take on the powerful Koopamancer!",
        description:
            "Can you defeat the powerful and menacing KOOPAMANCER?!\n\nThis Paper Mario 64 mod adds a whole new boss battle, 2 new badges specifically made for this boss fight and a new partner to help you.",
        game: "PM64",
        console: "N64",
        consoleCompatible: true,
        recommendedEmulator: "Ares",
        modGroup: "BattleJam2024",
    },
    vsluigi: {
        displayName: "Paper Mario vs Luigi",
        internalName: "vsluigi",
        creators: ["Darxoon"],
        releaseDate: "06/05/2024",
        lastUpdated: "06/05/2024",
        version: "1.0",
        pageUrl: "https://darxoon.itch.io/paper-mario-vs-luigi",
        downloadUrl: "https://darxoon.itch.io/paper-mario-vs-luigi",
        sourceUrl: "https://github.com/Darxoon/PMvL",
        iconUrl: "/src/routes/mods/assets/empty.webp?run&lqip=0",
        tagline: "Mario fights against... Luigi?",
        description:
            "Mario from the hit game Paper Mario fights against..... his brother Luigi?\n\nYou will never figure out why!",
        game: "PM64",
        console: "N64",
        consoleCompatible: true,
        recommendedEmulator: "Ares",
        modGroup: "BattleJam2024",
    },
    genomod: {
        displayName: "This is how we mod Paper Mario",
        internalName: "genomod",
        creators: ["Shyblookster137", "Rainchus"],
        releaseDate: "06/05/2024",
        lastUpdated: "06/05/2024",
        version: "1.0.9999",
        pageUrl:
            "https://shyblookster137.itch.io/this-is-how-we-mod-paper-mario",
        downloadUrl:
            "https://shyblookster137.itch.io/this-is-how-we-mod-paper-mario",
        sourceUrl:
            "https://github.com/ShyBlookster137/This_is_how_we_mod_Paper_Mario-Source",
        iconUrl: "/src/routes/mods/assets/empty.webp?run&lqip=0",
        tagline: "This is how...we advertise!",
        description:
            "An epic showdown between Mario and an old acquaintance.\n\nEnjoy one truly special battle against a special someone in this very special mod!",
        game: "PM64",
        console: "N64",
        consoleCompatible: true,
        recommendedEmulator: "Ares",
        modGroup: "BattleJam2024",
    },
    sullied: {
        displayName: "Sullied Grace",
        internalName: "sullied",
        creators: ["Asmodeus"],
        releaseDate: "06/05/2024",
        lastUpdated: "06/05/2024",
        version: "1.0",
        pageUrl: "https://soulmana.itch.io/paper-mario-64-mod-sullied-grace",
        downloadUrl:
            "https://soulmana.itch.io/paper-mario-64-mod-sullied-grace",
        sourceUrl: "https://github.com/Asmybelle/pm64-Sulliedgrace",
        iconUrl: "/src/routes/mods/assets/empty.webp?run&lqip=0",
        tagline: "Battle Queen Sectonia!",
        description:
            "My first paper mario 64 mod, made for the star haven jam 2024 on the theme 'battle'.\n\nI chose to implement a battle against Queen Sectonia from the kirby series, because I like the boss, and because her music is a banger. ",
        game: "PM64",
        console: "N64",
        consoleCompatible: true,
        recommendedEmulator: "Ares",
        modGroup: "BattleJam2024",
    },
    ramphase12: {
        displayName: "Rubies and Magic: Phase 1 + 2",
        internalName: "ramphase12",
        creators: ["l5050"],
        releaseDate: "06/05/2024",
        lastUpdated: "06/05/2024",
        version: "1.0",
        pageUrl: "https://l5050.itch.io/rubies-and-magic-phase-1",
        downloadUrl: "https://github.com/L5050/Hard-Mode-Rubies-and-Magic",
        sourceUrl:
            "https://github.com/L5050/Hard-Mode-Rubies-and-Magic/tree/master",
        iconUrl: "/src/routes/mods/assets/emptyspm.webp?run&lqip=0",
        tagline: "A custom Count Bleck boss fight!",
        description:
            "The first phase of a major update to hard mode, specifically the custom Count Bleck boss fight I made to replace the 8-4 fight. You can explore the world of hard mode if you want, or fight Super Dimentio.",
        game: "SPM",
        console: "Wii",
        consoleCompatible: true,
        recommendedEmulator: "Dolphin",
        modGroup: "BattleJam2024",
    },
    shiftt: {
        displayName: "Shift T. Showdown",
        internalName: "shiftt",
        creators: ["Enneagon"],
        releaseDate: "06/05/2024",
        lastUpdated: "06/05/2024",
        version: "1.0",
        pageUrl: "https://enneagon.itch.io/shift-t-showdown",
        downloadUrl: "https://enneagon.itch.io/shift-t-showdown",
        sourceUrl: "https://github.com/Enneagon/papervs",
        iconUrl: "/src/routes/mods/assets/empty.webp?run&lqip=0",
        tagline: "Mario takes on his greatest foe yet!",
        description:
            "Paper Mario faces off against the dank Toad of doom, Shift T.!\n\nIt'll take some true heroics to save the world from such a threat!",
        game: "PM64",
        console: "N64",
        consoleCompatible: true,
        recommendedEmulator: "Ares",
        modGroup: "BattleJam2024",
    },
};

export const arr = Object.values(obj);
